- hosts: indexer
  user: ec2-user
  become: yes
  
  tasks: 
    - name: Unarchive splunk tar
      ansible.builtin.unarchive:
          src: "https://download.splunk.com/products/splunk/releases/8.1.3/linux/splunk-8.1.3-63079c59e632-Linux-x86_64.tgz"
          dest: /opt/
          remote_src: yes
          owner: ec2-user
       
    - name: chown 
      command: chown -R ec2-user /opt/splunk/

    - name: Start Splunk and accept license
      tags:
        - install
      command: /opt/splunk/bin/./splunk start --accept-license --answer-yes --no-prompt
    
    - name: Create user
      copy:
          dest: /opt/splunk/etc/system/local/user-seed.conf
          content: |
            [user_info]
            USERNAME = admin
            PASSWORD = admin123
          owner: ec2-user
          

    - name: Change diskUsage parameter
      copy:
          dest: /opt/splunk/etc/system/local/server.conf
          content: |
            [diskUsage]
            minFreeSpace = 5
          
    - name: enable https
      copy: 
          dest: /opt/splunk/etc/system/local/web.conf
          content: |
             [settings]
             enableSplunkWebSSL = 1

    - name: Restart Splunk
      command: /opt/splunk/bin/./splunk restart
